name: flutter_ocr_firebase
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  camera: 0.5.8+11
  path_provider: ^1.6.21
  intl: ^0.16.1
  firebase_ml_vision: ^0.9.7
  firebase_core: ^0.5.0+1
  tflite: 1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.0

flutter_icons:
  android: launcher_icon
  ios: true
  image_path: assets/icon/icon.png

flutter:

  assets:
    - assets/yolov2_tiny.tflite
    - assets/yolov2_tiny.txt
    - assets/ssd_mobilenet.tflite
    - assets/ssd_mobilenet.txt

  uses-material-design: true
